### ISSUE TITLE
Phaser Flood game "monsters" randomly move out of position

### ISSUE THREAD

**Issue by zdaisyz** [nyu-ossd-s18/phaser-coord#3]
![screenshot 16](https://user-images.githubusercontent.com/5962606/37666645-6c7d1910-2c36-11e8-9c37-824b18fded18.png)

**Comment by melissaelopez** [comment]
We found that the issue has already been posted on the phaser3-examples repo, but has not yet been resolved: https://github.com/photonstorm/phaser3-examples/issues/22

**Comment by zdaisyz** [comment]
Closing since this is a duplicate
